// Generates src/components/basemap.generated.ts: the world's country outlines,
// so the site map has geography without asking anybody for tiles.
//
//   node scripts/gen-basemap.mjs
//
// Why not tiles. Street tiles come from someone else's server, and every tile is
// a request to a host the console would have to name in its content policy. The
// OpenStreetMap project's own servers refuse us outright — their policy requires
// an app to identify itself in the User-Agent, which a page in a browser cannot
// set — and the free alternatives either want a key or serve vector tiles, which
// need `connect-src` to a foreign host and `worker-src blob:`. That is a real
// exfiltration channel in exchange for street names nobody reads on this map.
//
// Coastlines and borders are enough to answer "where is it burning", they are
// public domain (Natural Earth, via world-atlas, ISC), and at this size they fit
// in the binary. An operator who wants streets sets `map.tiles` to a server they
// run or license; only then does the console name that host.

import { writeFileSync } from "node:fs"
import { readFileSync } from "node:fs"
import { createRequire } from "node:module"
import { feature } from "topojson-client"

const require = createRequire(import.meta.url)

// 1:110m is the coarse Natural Earth set: continents and countries, no islands
// smaller than a pixel at the zoom levels a site map ever uses.
const topo = JSON.parse(readFileSync(require.resolve("world-atlas/countries-110m.json"), "utf8"))
const fc = feature(topo, topo.objects.countries)

/** Coordinates to three decimals: about 100 m, far finer than a country outline needs. */
const round = (n) => Math.round(n * 1000) / 1000

function thin(coords) {
  if (typeof coords[0] === "number") return [round(coords[0]), round(coords[1])]
  return coords.map(thin)
}

// Names are not drawn, so they are not carried.
const features = fc.features.map((f) => ({
  type: "Feature",
  geometry: { type: f.geometry.type, coordinates: thin(f.geometry.coordinates) },
  properties: {},
}))

const out = `// GENERATED by scripts/gen-basemap.mjs — do not edit by hand.
//
// Country outlines from Natural Earth (public domain) via world-atlas, thinned to
// three decimals. Drawn by the site map instead of tiles from a foreign server:
// see the script's header for why that trade is made this way.

import type { FeatureCollection } from "geojson"

export const countries = ${JSON.stringify({ type: "FeatureCollection", features })} as unknown as FeatureCollection
`
writeFileSync(new URL("../src/components/basemap.generated.ts", import.meta.url), out)
console.log(`wrote ${features.length} countries, ${(out.length / 1024).toFixed(0)} kB`)
